### ISSUE TITLE
Should be upgraded to .net 6.0 as it is for LTS

### ISSUE THREAD

**Issue by KamranShahid** [baking-bad/netezos#45]
Should be upgraded to .net 6.0 as it is for LTS

**Comment by Groxan** [comment]
We would love to switch to .NET 6.0 as it's a kind of state of the art, but it would cause a lot of compatibility problems for Unity, WPF, and .NET Framework devs. .NET Standard 2.0 is also for LTS and is actually a better choice for building reusable libraries right now. Read more: https://docs.microsoft.com/dotnet/standard/net-standard?tabs=net-standard-2-0.

However, I'm not saying "no" :) I believe, we will eventually switch to .NET 6.0+ after it gets more adoption.

**Comment by KamranShahid** [comment]
Thanks Maksim,
I have fork the repository and upgraded all the nuget packages to latest one in all three projects.
At the moment I have not change the .net standard version from 2.0 to 2.1 as i am still in learning phase of this tezos. will do that later in my repo
Thanks
