### ISSUE TITLE
Bls12381 curve slip10 implentation? 

### ISSUE THREAD

**Issue by kzorin52** [baking-bad/netezos#60]
Are there any plans to do so?

**Comment by Groxan** [comment]
Slip10 doesn't support bls12381, according to the specification:
> The supported curves are
> - Curve = "Bitcoin seed" for the secp256k1 curve (this is compatible with BIP-0032).
> - Curve = "Nist256p1 seed" for the NIST P-256 curve.
> - Curve = "ed25519 seed" for the ed25519 curve.

**Comment by kzorin52** [comment]
I see, thx
